//
//  TestModel.swift
//  History Fight Ninja
//
//  Created by Anatolii Kravchuk on 27.09.2024.
//

import Foundation

class AppState: ObservableObject {
    @Published var countries: [String] = [
        "Greenland",
        "Iceland",
        "Portugal",
        "Morocco",
        "Spain",
        "Tunisia",
        "Algeria",
        "Belgium",
        "Italy",
        "Belarus",
        "Poland",
        "Jordan",
        "Turkmenistan",
        "Kazakhstan",
        "Finland",
        "Germany",
        "Sweden",
        "Norway",
        "Ukraine",
        "Israel",
        "Saudi Arabia",
        "Iraq",
        "Azerbaijan",
        "Iran",
        "Georgia",
        "Syria",
        "Turkey",
        "Armenia",
        "Cyprus",
        "Ireland",
        "United Kingdom",
        "Switzerland",
        "Austria",
        "Czech Republic",
        "Slovakia",
        "Hungary",
        "Lithuania",
        "Russia",
        "Latvia",
        "Moldova",
        "Romania",
        "Bulgaria",
        "Albania",
        "Estonia",
        "Lebanon",
        "Andorra",
        "San Marino",
        "Monaco",
        "Luxembourg",
        "France",
        "Liechtenstein",
        "Netherlands",
        "Bosnia and Herzegovina",
        "Slovenia",
        "North Macedonia",
        "Croatia",
        "Denmark",
        "Malta",
        "Montenegro",
        "Suriname",
        "Greece",
        "Isle of Man",
        "Vatican City",
        "Great Britain",
        "Serbia",
        "Kosovo",
        "Western Sahara",
        "Libya",
        "Egypt",
        "Sudan",
        "Chad",
        "Niger",
        "Mali",
        "Mauritania",
        "Senegal",
        "Guinea",
        "Liberia",
        "Côte d'Ivoire",
        "Ghana",
        "Burkina Faso",
        "Sierra Leone",
        "Guinea-Bissau",
        "Togo",
        "Benin",
        "Nigeria",
        "Cameroon",
        "Central African Republic",
        "South Sudan",
        "Ethiopia",
        "Colombia",
        "Eritrea",
        "Djibouti",
        "Kenya",
        "Equatorial Guinea",
        "Gabon",
        "Republic of the Congo",
        "Democratic Republic of the Congo",
        "Uganda",
        "Angola",
        "Zambia",
        "Malawi",
        "Mozambique",
        "Zimbabwe",
        "Botswana",
        "Namibia",
        "South Africa",
        "Madagascar",
        "Somalia",
        "Tanzania",
        "Rwanda",
        "Yemen",
        "Oman",
        "United Arab Emirates",
        "Qatar",
        "Kuwait",
        "State of Palestine",
        "Afghanistan",
        "Uzbekistan",
        "Kyrgyzstan",
        "Tajikistan",
        "Pakistan",
        "India",
        "Nepal",
        "Bhutan",
        "Mongolia",
        "China",
        "Myanmar",
        "Bangladesh",
        "Thailand",
        "Cambodia",
        "Vietnam",
        "Laos",
        "Malaysia",
        "Indonesia",
        "Papua New Guinea",
        "Solomon Islands",
        "New Caledonia",
        "Fiji",
        "Australia",
        "New Zealand",
        "French Southern and Antarctic Territories",
        "Vanuatu",
        "South Korea",
        "North Korea",
        "Japan",
        "Taiwan",
        "Philippines",
        "Sri Lanka",
        "Timor-Leste",
        "Falkland Islands",
        "Argentina",
        "Chile",
        "Uruguay",
        "Brazil",
        "Bolivia",
        "Paraguay",
        "Peru",
        "Ecuador",
        "Venezuela",
        "Guyana",
        "French Guiana",
        "Trinidad and Tobago",
        "Panama",
        "Costa Rica",
        "Nicaragua",
        "Honduras",
        "Belize",
        "Mexico",
        "Cuba",
        "Haiti",
        "Jamaica",
        "Dominican Republic",
        "Puerto Rico",
        "Bahamas",
        "United States",
        "Canada",
        "Gambia",
        "Lesotho",
        "Eswatini",
        "Brunei",
        "Guatemala",
        "El Salvador"
        ]
}
