////
////  Economic.swift
////  History Fight Ninja
////
////  Created by Anatolii Kravchuk on 06.08.2024.
////
//
import SwiftUI

    func defaultEconomySkills(manager: SkillTreeManager) -> [Skill] {
        let economic = UUID()                // 50
        
        let manufacturing = UUID()          //100
        let automation = UUID()             //250
        let modernTech = UUID()             //250
        let massProduction = UUID()         //250
        let savingResources = UUID()        //350
        let innovation = UUID()             //350
        let robotization = UUID()           //450
        let internationalization = UUID()   //500
                                            //Total: 2500
        let trading = UUID()
        let tradeAgreements = UUID()
        let logistics = UUID()
        let tradeMissions = UUID()
        let freeTradeZones = UUID()
        let tourism = UUID()
        let expansion = UUID()
        let exhibition = UUID() //TODO: add image and description
        
        let globalAlliances = UUID()        //1000
        
        return [
            Skill(id: economic,
                  name: "Economic",
                  description: "Income + 5",
                  branch: .economy,
                  baseCost: 50,
                  cost: 50,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "Economic",
                  actionKey: "increaseIncomeBy5",
                  dependencies: [],
                  position: CGPoint(x: 0.55, y: 0.01)),
// Manufacturing:
            Skill(id: manufacturing,
                  name: "Manufacturing",
                  description: "Reduces costs -5%",
                  branch: .economy,
                  baseCost: 100,
                  cost: Int(round(100 * manager.priceCoefficient)),
                  isUnlocked: false,
                  isPurchased: false,
                  imageName: "ManufacturingBasics",
                  actionKey: "reduceCostsBy5",
                  dependencies: [economic],
                  position: CGPoint(x: 0.35, y: 0.1)),
            Skill(id: automation,
                  name: "Automation",
                  description: "Income + 3",
                  branch: .economy,
                  baseCost: 250,
                  cost: 250,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "EconomcBasicsAutomation",
                  actionKey: "increaseIncomeBy3",
                  dependencies: [manufacturing],
                  position: CGPoint(x: 0.15, y: 0.2)),
            Skill(id: modernTech,
                  name: "Modern Tech",
                  description: "Reduces costs -2%",
                  branch: .economy,
                  baseCost: 250,
                  cost: 250,
                  isUnlocked: false,
                  isPurchased: false,
                  imageName: "ModernTechnologies",
                  actionKey: "reduceCostsBy2",
                  dependencies: [manufacturing],
                  position: CGPoint(x: 0.30, y: 0.2)),
            Skill(id: massProduction,
                  name: "Mass Production",
                  description: "Reduces costs -2%",
                  branch: .economy,
                  baseCost: 250,
                  cost: 250,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "MassProduction",
                  actionKey: "reduceCostsBy2",
                  dependencies: [manufacturing],
                  position: CGPoint(x: 0.45, y: 0.2)),
            Skill(id: savingResources,
                  name: "Saving Resources",
                  description: "Income + 5",
                  branch: .economy,
                  baseCost: 350,
                  cost: 350,
                  isUnlocked: false,
                  isPurchased: false,
                  imageName: "SavingResources",
                  actionKey: "increaseIncome",
                  dependencies: [automation],
                  position: CGPoint(x: 0.15, y: 0.3)),
            Skill(id: innovation,
                  name: "Innovation",
                  description: "Reduces costs -3%",
                  branch: .economy,
                  baseCost: 350,
                  cost: 350,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "Innovation",
                  actionKey: "reduceCostsBy3",
                  dependencies: [modernTech],
                  position: CGPoint(x: 0.3, y: 0.3)),
            Skill(id: robotization,
                  name: "Robotization",
                  description: "Reduces costs -3%",
                  branch: .economy,
                  baseCost: 450,
                  cost: 450,
                  isUnlocked: false,
                  isPurchased: false,
                  imageName: "Robotization",
                  actionKey: "reduceCostsBy3",
                  dependencies: [innovation, massProduction],
                  position: CGPoint(x: 0.45, y: 0.3)),
            Skill(id: internationalization,
                  name: "Internationalization",
                  description: "Max Energy + 1",
                  branch: .economy,
                  baseCost: 500,
                  cost: 500,
                  isUnlocked: false,
                  isPurchased: false,
                  imageName: "Internationalization",
                  actionKey: "increaseEnergy1",
                  dependencies: [savingResources],
                  position: CGPoint(x: 0.37, y: 0.37)),
// Traidng:
            Skill(id: trading,
                  name: "Trading",
                  description: "Prize for victory +3%",
                  branch: .economy,
                  baseCost: 100,
                  cost: 100,
                  isUnlocked: false,
                  isPurchased: false,
                  imageName: "Trading",
                  actionKey: "prizeVictory3",
                  dependencies: [economic],
                  position: CGPoint(x: 0.75, y: 0.1)),
            
            Skill(id: tradeAgreements,
                  name: "Trade agreements",
                  description: "Prize for victory +2%",
                  branch: .economy,
                  baseCost: 250,
                  cost: 250,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "TradeAgreements",
                  actionKey: "prizeVictory2",
                  dependencies: [trading],
                  position: CGPoint(x: 0.65, y: 0.2)),
            
            Skill(id: logistics,
                  name: "Logistics",
                  description: "Prize for victory +2%",
                  branch: .economy,
                  baseCost: 250,
                  cost: 250,
                  isUnlocked: false,
                  isPurchased: false,
                  imageName: "logistics",
                  actionKey: "prizeVictory2",
                  dependencies: [trading],
                  position: CGPoint(x: 0.80, y: 0.2)),
            
            Skill(id: tradeMissions,
                  name: "Trade missions",
                  description: "Income + 2",
                  branch: .economy,
                  baseCost: 250,
                  cost: 250,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "TradeMissions",
                  actionKey: "increaseIncomeBy2",
                  dependencies: [trading],
                  position: CGPoint(x: 0.95, y: 0.2)),
            
            Skill(id: freeTradeZones,
                  name: "Free Trade Zones",
                  description: "Prize for victory +3%",
                  branch: .economy,
                  baseCost: 250,
                  cost: 350,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "FreeTradeZones",
                  actionKey: "prizeVictory3",
                  dependencies: [tradeAgreements, tourism],
                  position: CGPoint(x: 0.65, y: 0.3)),
            
            Skill(id: tourism,
                  name: "Tourism development",
                  description: "Prize for victory +3%",
                  branch: .economy,
                  baseCost: 350,
                  cost: 350,
                  isUnlocked: false,
                  isPurchased: false,
                  imageName: "TourismDevelopment",
                  actionKey: "prizeVictory3",
                  dependencies: [logistics],
                  position: CGPoint(x: 0.80, y: 0.3)),
            
            Skill(id: expansion,
                  name: "Expansion",
                  description: "Income + 5",
                  branch: .economy,
                  baseCost: 450,
                  cost: 450,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "GlobalExpansion",
                  actionKey: "increaseIncomeBy5",
                  dependencies: [tradeMissions],
                  position: CGPoint(x: 0.95, y: 0.3)),
            
            Skill(id: exhibition,
                  name: "Trade missions",
                  description: "Max Energy +1",
                  branch: .economy,
                  baseCost: 500,
                  cost: 500,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "Exhibition",
                  actionKey: "increaseEnergy1",
                  dependencies: [expansion],
                  position: CGPoint(x: 0.73, y: 0.37)),
            
            Skill(id: globalAlliances,
                  name: "Global Alliances",
                  description: "Max Energy +3",
                  branch: .economy,
                  baseCost: 1000,
                  cost: 1000,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "GlobalStrategicAlliances",
                  actionKey: "increaseEnergy3",
                  dependencies: [internationalization, exhibition],
                  position: CGPoint(x: 0.55, y: 0.45))
        ]
    }

