////
////  Army.swift
////  History Fight Ninja
////
////  Created by Anatolii Kravchuk on 06.08.2024.
////
//
import Foundation
import SwiftUI

    func defaultArmySkills(manager: SkillTreeManager) -> [Skill] {
        let military = UUID()
        
        let shooting = UUID()
        let tactics = UUID()
        let intelligence = UUID()
        let defense = UUID()
        let flanking = UUID()
        let artillery = UUID()
        let navalForces = UUID()
        
        let airForces = UUID()
        
        let supply = UUID()
        
        let milLogistics = UUID()
        let transportation = UUID()
        let medicalServices = UUID()
        
        let repair = UUID()
        let modernShelters = UUID()
        let drones = UUID()
        
        let spaceForces = UUID()
        
        let wrathOfGod = UUID()
        
        return [
            Skill(id: military,
                  name: "Military",
                  description: "Max Health +2",
                  branch: .army,
                  baseCost: 50,
                  cost: 50,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "warCraft",
                  actionKey: "increaseMaxHealth2",
                  dependencies: [],
                  position: CGPoint(x: 0.55, y: 0.01)),
            //MARK: - tactics:
            Skill(id: shooting,
                  name: "Shooting",
                  description: "Attack +3",
                  branch: .army,
                  baseCost: 100,
                  cost: 100,
                  isUnlocked: false,
                  isPurchased: false,
                  imageName: "shooting",
                  actionKey:  "increaseAttack3",
                  dependencies: [military],
                  position: CGPoint(x: 0.35, y: 0.1)),
            Skill(id: intelligence,
                  name: "Intelligence",
                  description: "Attack +3",
                  branch: .army,
                  baseCost: 250,
                  cost: 250,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "intelligence",
                  actionKey: "increaseAttack3",
                  dependencies: [shooting],
                  position: CGPoint(x: 0.15, y: 0.2)),
            Skill(id: tactics,
                  name: "Tactics",
                  description: "Attack +3",
                  branch: .army,
                  baseCost: 250,
                  cost: 250,
                  isUnlocked: false,
                  isPurchased: false,
                  imageName: "tactical",
                  actionKey: "increaseAttack3",
                  dependencies: [shooting],
                  position: CGPoint(x: 0.30, y: 0.2)),
            Skill(id: defense,
                  name: "Defense",
                  description: "Max Health +1",
                  branch: .army,
                  baseCost: 250,
                  cost: 250,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "defense",
                  actionKey: "increaseMaxHealth1",
                  dependencies: [shooting],
                  position: CGPoint(x: 0.45, y: 0.2)),
            Skill(id: flanking,
                  name: "Flanking attack",
                  description: "Attack +5",
                  branch: .army,
                  baseCost: 350,
                  cost: 350,
                  isUnlocked: false,
                  isPurchased: false,
                  imageName: "flanking",
                  actionKey: "increaseAttack5",
                  dependencies: [intelligence],
                  position: CGPoint(x: 0.15, y: 0.3)),
            Skill(id: artillery,
                  name: "Artillery",
                  description: "Attack +5",
                  branch: .army,
                  baseCost: 350,
                  cost: 350,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "artillery",
                  actionKey: "increaseAttack5",
                  dependencies: [tactics],
                  position: CGPoint(x: 0.3, y: 0.3)),
            Skill(id: navalForces,
                  name: "Naval forces",
                  description: "Attack +10",
                  branch: .army,
                  baseCost: 350,
                  cost: 350,
                  isUnlocked: false,
                  isPurchased: false, imageName: "naval",
                  actionKey: "increaseAttack10",
                  dependencies: [defense, artillery],
                  position: CGPoint(x: 0.45, y: 0.3)),
            Skill(id: airForces,
                  name: "Air forces",
                  description: "Attack +5",
                  branch: .army,
                  baseCost: 450,
                  cost: 450,
                  isUnlocked: false,
                  isPurchased: false,
                  imageName: "aerial",
                  actionKey: "increaseAttack5",
                  dependencies: [flanking],
                  position: CGPoint(x: 0.37, y: 0.37)),
//            //MARK: - Supply:
            Skill(id: supply,
                  name: "Army Supply",
                  description: "Max Streak +1",
                  branch: .army,
                  baseCost: 100,
                  cost: 100,
                  isUnlocked: false,
                  isPurchased: false,
                  imageName: "ArmySupply",
                  actionKey: "increaseMaxStreak1",
                  dependencies: [military],
                  position: CGPoint(x: 0.75, y: 0.1)),
            
            Skill(id: milLogistics,
                  name: "Military logistics",
                  description: "Max Streak +1",
                  branch: .army,
                  baseCost: 250,
                  cost: 250,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "logisticsArmy",
                  actionKey: "increaseMaxStreak1",
                  dependencies: [supply],
                  position: CGPoint(x: 0.65, y: 0.2)),
            Skill(id: transportation,
                  name: "Logistics",
                  description: "Max Streak +1",
                  branch: .army,
                  baseCost: 250,
                  cost: 250,
                  isUnlocked: false,
                  isPurchased: false,
                  imageName: "transportation",
                  actionKey: "increaseMaxStreak1",
                  dependencies: [supply],
                  position: CGPoint(x: 0.80, y: 0.2)),
            Skill(id: medicalServices,
                  name: "Medical Services",
                  description: "Max Streak +1",
                  branch: .army,
                  baseCost: 250,
                  cost: 250,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "medicalServices",
                  actionKey: "increaseMaxStreak1",
                  dependencies: [supply],
                  position: CGPoint(x: 0.95, y: 0.2)),
            
            Skill(id: repair,
                  name: "Repair",
                  description: "???",
                  branch: .army,
                  baseCost: 350,
                  cost: 350,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "repair",
                  actionKey: "",
                  dependencies: [milLogistics, modernShelters],
                  position: CGPoint(x: 0.65, y: 0.3)),
            
            Skill(id: modernShelters,
                  name: "Modern Shelters",
                  description: "???",
                  branch: .army,
                  baseCost: 350,
                  cost: 350,
                  isUnlocked: false,
                  isPurchased: false,
                  imageName: "modernShelters",
                  actionKey: "",
                  dependencies: [transportation],
                  position: CGPoint(x: 0.80, y: 0.3)),
            
            Skill(id: drones,
                  name: "Drones",
                  description: "???",
                  branch: .army,
                  baseCost: 350,
                  cost: 350,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "drones",
                  actionKey: "",
                  dependencies: [medicalServices],
                  position: CGPoint(x: 0.95, y: 0.3)),
            
            Skill(id: spaceForces,
                  name: "Space Forces",
                  description: "??",
                  branch: .army,
                  baseCost: 350,
                  cost: 350,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "spaceForces",
                  actionKey: "",
                  dependencies: [drones],
                  position: CGPoint(x: 0.73, y: 0.37)),
            
            Skill(id: wrathOfGod,
                  name: "Wrath Of God",
                  description: "Give WoG to in battle",
                  branch: .army,
                  baseCost: 1000,
                  cost: 1000,
                  isUnlocked: true,
                  isPurchased: false,
                  imageName: "WrathOfGod",
                  actionKey: "",
                  dependencies: [airForces, spaceForces],
                  position: CGPoint(x: 0.55, y: 0.45))
        ]
    }

//
//let militaryStageSeven = SkillModel(name: "Air forces",
//                                    description: "Сolonies income +4",
//                                    cost: 120,
//                                    imageName: "aerial",
//                                    isUnlocked: false,
//                                    isAviable: true,
//                                    requiredSkill: [militaryStageSix.id],
//                                    action: {})
