//
//  MapsModelData.swift
//  History Fight Ninja
//
//  Created by Anatolii Kravchuk on 10.05.2024.
//

import Foundation

class MapsModelData: ObservableObject {
    @Published var countriesDict: [String: String] = [
        "GL": "Greenland",
        "IS": "Iceland",
        "PT": "Portugal",
        "MA": "Morocco",
        "ES": "Spain",
        "TN": "Tunisia",
        "DZ": "Algeria",
        "BE": "Belgium",
        "IT": "Italy",
        "BY": "Belarus",
        "PL": "Poland",
        "JO": "Jordan",
        "TM": "Turkmenistan",
        "KZ": "Kazakhstan",
        "FI": "Finland",
        "DE": "Germany",
        "SE": "Sweden",
        "NO": "Norway",
        "UA": "Ukraine",
        "IL": "Israel",
        "SA": "Saudi Arabia",
        "IQ": "Iraq",
        "AZ": "Azerbaijan",
        "IR": "Iran",
        "GE": "Georgia",
        "SY": "Syria",
        "TR": "Turkey",
        "AM": "Armenia",
        "CY": "Cyprus",
        "IE": "Ireland",
        "UK": "United Kingdom",
        "CH": "Switzerland",
        "AT": "Austria",
        "CZ": "Czech Republic",
        "SK": "Slovakia",
        "HU": "Hungary",
        "LT": "Lithuania",
        "RU": "Russia",
        "LV": "Latvia",
        "MD": "Moldova",
        "RO": "Romania",
        "BG": "Bulgaria",
        "AL": "Albania",
        "EE": "Estonia",
        "LB": "Lebanon",
        "AD": "Andorra",
        "SM": "San Marino",
        "MC": "Monaco",
        "LU": "Luxembourg",
        "FR": "France",
        "LI": "Liechtenstein",
        "NL": "Netherlands",
        "BA": "Bosnia and Herzegovina",
        "SI": "Slovenia",
        "MK": "North Macedonia",
        "HR": "Croatia",
        "DK": "Denmark",
        "MT": "Malta",
        "ME": "Montenegro",
        "SR": "Suriname",
        "GR": "Greece",
        "IM": "Isle of Man",
        "VA": "Vatican City",
        "GB": "Great Britain",
        "RS": "Serbia",
        "XK": "Kosovo",
        "SJ": "Norway",
        "EH": "Western Sahara",
        "LY": "Libya",
        "EG": "Egypt",
        "SD": "Sudan",
        "TD": "Chad",
        "NE": "Niger",
        "ML": "Mali",
        "MR": "Mauritania",
        "SN": "Senegal",
        "GN": "Guinea",
        "LR": "Liberia",
        "CI": "Côte d'Ivoire",
        "GH": "Ghana",
        "BF": "Burkina Faso",
        "SL": "Sierra Leone",
        "GW": "Guinea-Bissau",
        "TG": "Togo",
        "BJ": "Benin",
        "NG": "Nigeria",
        "CM": "Cameroon",
        "CF": "Central African Republic",
        "SS": "South Sudan",
        "ET": "Ethiopia",
        "CO": "Colombia",
        "ER": "Eritrea",
        "SO": "Somalia",
        "DJ": "Djibouti",
        "KE": "Kenya",
        "GQ": "Equatorial Guinea",
        "GA": "Gabon",
        "CG": "Republic of the Congo",
        "CD": "Democratic Republic of the Congo",
        "UG": "Uganda",
        "AO": "Angola",
        "ZM": "Zambia",
        "MW": "Malawi",
        "MZ": "Mozambique",
        "ZW": "Zimbabwe",
        "BW": "Botswana",
        "NA": "Namibia",
        "ZA": "South Africa",
        "MG": "Madagascar",
        "TZ": "Tanzania",
        "RW": "Rwanda",
        "YE": "Yemen",
        "OM": "Oman",
        "AE": "United Arab Emirates",
        "QA": "Qatar",
        "KW": "Kuwait",
        "PS": "State of Palestine",
        "AF": "Afghanistan",
        "UZ": "Uzbekistan",
        "KG": "Kyrgyzstan",
        "TJ": "Tajikistan",
        "PK": "Pakistan",
        "IN": "India",
        "NP": "Nepal",
        "BT": "Bhutan",
        "MN": "Mongolia",
        "CN": "China",
        "MM": "Myanmar",
        "BD": "Bangladesh",
        "TH": "Thailand",
        "KH": "Cambodia",
        "VN": "Vietnam",
        "LA": "Laos",
        "MY": "Malaysia",
        "ID": "Indonesia",
        "PG": "Papua New Guinea",
        "SB": "Solomon Islands",
        "NC": "New Caledonia",
        "FJ": "Fiji",
        "AU": "Australia",
        "NZ": "New Zealand",
        "TF": "French Southern and Antarctic Territories",
        "VU": "Vanuatu",
        "KR": "South Korea",
        "KP": "North Korea",
        "JP": "Japan",
        "TW": "Taiwan",
        "PH": "Philippines",
        "LK": "Sri Lanka",
        //point
        "TL": "Timor-Leste",
        "FK": "Falkland Islands",
        "AR": "Argentina",
        "CL": "Chile",
        "UY": "Uruguay",
        "BR": "Brazil",
        "BO": "Bolivia",
        "PY": "Paraguay",
        "PE": "Peru",
        "EC": "Ecuador",
        "VE": "Venezuela",
        "GY": "Guyana",
        "GF": "French Guiana",
        "TT": "Trinidad and Tobago",
        "PA": "Panama",
        "CR": "Costa Rica",
        "NI": "Nicaragua",
        "HN": "Honduras",
        "BZ": "Belize",
        "MX": "Mexico",
        "CU": "Cuba",
        "HT": "Haiti",
        "JM": "Jamaica",
        "DO": "Dominican Republic",
        "PR": "Puerto Rico",
        "BS": "Bahamas",
        "US": "United States",
        "CA": "Canada"
    ]
}

