import Foundation

//countriesData = [
//    MapCountryModel(countryCode: "GL", name: "Greenland", color: .grey, power: 10),
//    MapCountryModel(countryCode: "IS", name: "Iceland", color: .grey, power: 20),
//    MapCountryModel(countryCode: "PT", name: "Portugal", color: .grey, power: 50),
//    MapCountryModel(countryCode: "MA", name: "Morocco", color: .grey, power: 70),
//    MapCountryModel(countryCode: "ES", name: "Spain", color: .grey, power: 200),
//    MapCountryModel(countryCode: "TN", name: "Tunisia", color: .grey, power: 60),
//    MapCountryModel(countryCode: "DZ", name: "Algeria", color: .grey, power: 100),
//    MapCountryModel(countryCode: "BE", name: "Belgium", color: .grey, power: 150),
//    MapCountryModel(countryCode: "IT", name: "Italy", color: .grey, power: 300),
//    MapCountryModel(countryCode: "BY", name: "Belarus", color: .grey, power: 80),
//    MapCountryModel(countryCode: "PL", name: "Poland", color: .grey, power: 150),
//    MapCountryModel(countryCode: "JO", name: "Jordan", color: .grey, power: 40),
//    MapCountryModel(countryCode: "TM", name: "Turkmenistan", color: .grey, power: 30),
//    MapCountryModel(countryCode: "KZ", name: "Kazakhstan", color: .grey, power: 90),
//    MapCountryModel(countryCode: "FI", name: "Finland", color: .grey, power: 100),
//    MapCountryModel(countryCode: "DE", name: "Germany", color: .grey, power: 800),
//    MapCountryModel(countryCode: "SE", name: "Sweden", color: .grey, power: 200),
//    MapCountryModel(countryCode: "NO", name: "Norway", color: .grey, power: 120),
//    MapCountryModel(countryCode: "UA", name: "Ukraine", color: .green, power: 200),
//    MapCountryModel(countryCode: "IL", name: "Israel", color: .grey, power: 250),
//    MapCountryModel(countryCode: "SA", name: "Saudi Arabia", color: .grey, power: 300),
//    MapCountryModel(countryCode: "IQ", name: "Iraq", color: .grey, power: 130),
//    MapCountryModel(countryCode: "AZ", name: "Azerbaijan", color: .grey, power: 70),
//    MapCountryModel(countryCode: "IR", name: "Iran", color: .grey, power: 300),
//    MapCountryModel(countryCode: "GE", name: "Georgia", color: .grey, power: 50),
//    MapCountryModel(countryCode: "SY", name: "Syria", color: .grey, power: 60),
//    MapCountryModel(countryCode: "TR", name: "Turkey", color: .grey, power: 400),
//    MapCountryModel(countryCode: "AM", name: "Armenia", color: .grey, power: 40),
//    MapCountryModel(countryCode: "CY", name: "Cyprus", color: .grey, power: 30),
//    MapCountryModel(countryCode: "IE", name: "Ireland", color: .grey, power: 150),
//    MapCountryModel(countryCode: "UK", name: "United Kingdom", color: .grey, power: 700),
//    MapCountryModel(countryCode: "CH", name: "Switzerland", color: .grey, power: 200),
//    MapCountryModel(countryCode: "AT", name: "Austria", color: .grey, power: 120),
//    MapCountryModel(countryCode: "CZ", name: "Czech Republic", color: .grey, power: 100),
//    MapCountryModel(countryCode: "SK", name: "Slovakia", color: .grey, power: 80),
//    MapCountryModel(countryCode: "HU", name: "Hungary", color: .grey, power: 90),
//    MapCountryModel(countryCode: "LT", name: "Lithuania", color: .grey, power: 60),
//    MapCountryModel(countryCode: "RU", name: "Russia", color: .grey, power: 1000),
//    MapCountryModel(countryCode: "LV", name: "Latvia", color: .grey, power: 50),
//    MapCountryModel(countryCode: "MD", name: "Moldova", color: .grey, power: 40),
//    MapCountryModel(countryCode: "RO", name: "Romania", color: .grey, power: 150),
//    MapCountryModel(countryCode: "BG", name: "Bulgaria", color: .grey, power: 90),
//    MapCountryModel(countryCode: "AL", name: "Albania", color: .grey, power: 30),
//    MapCountryModel(countryCode: "EE", name: "Estonia", color: .grey, power: 40),
//    MapCountryModel(countryCode: "LB", name: "Lebanon", color: .grey, power: 50),
//    MapCountryModel(countryCode: "AD", name: "Andorra", color: .grey, power: 20),
//    MapCountryModel(countryCode: "SM", name: "San Marino", color: .grey, power: 10),
//    MapCountryModel(countryCode: "MC", name: "Monaco", color: .grey, power: 20),
//    MapCountryModel(countryCode: "LU", name: "Luxembourg", color: .grey, power: 40),
//    MapCountryModel(countryCode: "FR", name: "France", color: .grey, power: 700),
//    MapCountryModel(countryCode: "LI", name: "Liechtenstein", color: .grey, power: 10),
//    MapCountryModel(countryCode: "NL", name: "Netherlands", color: .grey, power: 300),
//    MapCountryModel(countryCode: "BA", name: "Bosnia and Herzegovina", color: .grey, power: 60),
//    MapCountryModel(countryCode: "SI", name: "Slovenia", color: .grey, power: 70),
//    MapCountryModel(countryCode: "MK", name: "North Macedonia", color: .grey, power: 40),
//    MapCountryModel(countryCode: "HR", name: "Croatia", color: .grey, power: 80),
//    MapCountryModel(countryCode: "DK", name: "Denmark", color: .grey, power: 150),
//    MapCountryModel(countryCode: "MT", name: "Malta", color: .grey, power: 30),
//    MapCountryModel(countryCode: "ME", name: "Montenegro", color: .grey, power: 50),
//    MapCountryModel(countryCode: "RS", name: "Serbia", color: .grey, power: 90),
//    MapCountryModel(countryCode: "XK", name: "Kosovo", color: .grey, power: 30),
//    MapCountryModel(countryCode: "EH", name: "Western Sahara", color: .grey, power: 20),
//    MapCountryModel(countryCode: "LY", name: "Libya", color: .grey, power: 80),
//    MapCountryModel(countryCode: "EG", name: "Egypt", color: .grey, power: 150),
//    MapCountryModel(countryCode: "SD", name: "Sudan", color: .grey, power: 60),
//    MapCountryModel(countryCode: "TD", name: "Chad", color: .grey, power: 50),
//    MapCountryModel(countryCode: "CM", name: "Cameroon", color: .grey, power: 90),
//    MapCountryModel(countryCode: "NG", name: "Nigeria", color: .grey, power: 250),
//    MapCountryModel(countryCode: "GH", name: "Ghana", color: .grey, power: 80),
//    MapCountryModel(countryCode: "BJ", name: "Benin", color: .grey, power: 40),
//    MapCountryModel(countryCode: "ZA", name: "South Africa", color: .grey, power: 300),
//    MapCountryModel(countryCode: "NA", name: "Namibia", color: .grey, power: 50),
//    MapCountryModel(countryCode: "ZW", name: "Zimbabwe", color: .grey, power: 40),
//    MapCountryModel(countryCode: "TZ", name: "Tanzania", color: .grey, power: 100),
//    MapCountryModel(countryCode: "KE", name: "Kenya", color: .grey, power: 150),
//    MapCountryModel(countryCode: "UG", name: "Uganda", color: .grey, power: 60),
//    MapCountryModel(countryCode: "RW", name: "Rwanda", color: .grey, power: 30),
//    MapCountryModel(countryCode: "ET", name: "Ethiopia", color: .grey, power: 120),
//    MapCountryModel(countryCode: "ER", name: "Eritrea", color: .grey, power: 40),
//    MapCountryModel(countryCode: "DJ", name: "Djibouti", color: .grey, power: 20),
//    MapCountryModel(countryCode: "SO", name: "Somalia", color: .grey, power: 50),
//    MapCountryModel(countryCode: "US", name: "United States", color: .grey, power: 1000),
//    MapCountryModel(countryCode: "CA", name: "Canada", color: .grey, power: 800),
//    MapCountryModel(countryCode: "MX", name: "Mexico", color: .grey, power: 300),
//    MapCountryModel(countryCode: "GT", name: "Guatemala", color: .grey, power: 60),
//    MapCountryModel(countryCode: "HN", name: "Honduras", color: .grey, power: 50),
//    MapCountryModel(countryCode: "CR", name: "Costa Rica", color: .grey, power: 40),
//    MapCountryModel(countryCode: "PA", name: "Panama", color: .grey, power: 30),
//    MapCountryModel(countryCode: "CU", name: "Cuba", color: .grey, power: 70),
//    MapCountryModel(countryCode: "DO", name: "Dominican Republic", color: .grey, power: 60),
//    MapCountryModel(countryCode: "JM", name: "Jamaica", color: .grey, power: 40),
//    MapCountryModel(countryCode: "BR", name: "Brazil", color: .grey, power: 500),
//    MapCountryModel(countryCode: "AR", name: "Argentina", color: .grey, power: 300),
//    MapCountryModel(countryCode: "CO", name: "Colombia", color: .grey, power: 150),
//    MapCountryModel(countryCode: "PE", name: "Peru", color: .grey, power: 100),
//    MapCountryModel(countryCode: "VE", name: "Venezuela", color: .grey, power: 120),
//    MapCountryModel(countryCode: "CL", name: "Chile", color: .grey, power: 80),
//    MapCountryModel(countryCode: "EC", name: "Ecuador", color: .grey, power: 70),
//    MapCountryModel(countryCode: "PY", name: "Paraguay", color: .grey, power: 50),
//    MapCountryModel(countryCode: "BO", name: "Bolivia", color: .grey, power: 60),
//    MapCountryModel(countryCode: "UY", name: "Uruguay", color: .grey, power: 40),
//    MapCountryModel(countryCode: "GY", name: "Guyana", color: .grey, power: 30),
//    MapCountryModel(countryCode: "SR", name: "Suriname", color: .grey, power: 20),
//    MapCountryModel(countryCode: "AU", name: "Australia", color: .grey, power: 400),
//    MapCountryModel(countryCode: "NZ", name: "New Zealand", color: .grey, power: 150),
//    MapCountryModel(countryCode: "FJ", name: "Fiji", color: .grey, power: 30),
//    MapCountryModel(countryCode: "PG", name: "Papua New Guinea", color: .grey, power: 40),
//    MapCountryModel(countryCode: "SB", name: "Solomon Islands", color: .grey, power: 20),
//    MapCountryModel(countryCode: "VU", name: "Vanuatu", color: .grey, power: 10),
//    MapCountryModel(countryCode: "AS", name: "American Samoa", color: .grey, power: 10),
//    MapCountryModel(countryCode: "WS", name: "Samoa", color: .grey, power: 15),
//    MapCountryModel(countryCode: "TO", name: "Tonga", color: .grey, power: 10),
//    MapCountryModel(countryCode: "CK", name: "Cook Islands", color: .grey, power: 10),
//    MapCountryModel(countryCode: "NU", name: "Niue", color: .grey, power: 5),
//    MapCountryModel(countryCode: "TK", name: "Tokelau", color: .grey, power: 5),
//    MapCountryModel(countryCode: "PF", name: "French Polynesia", color: .grey, power: 25),
//    MapCountryModel(countryCode: "NC", name: "New Caledonia", color: .grey, power: 20),
//    MapCountryModel(countryCode: "WF", name: "Wallis and Futuna", color: .grey, power: 5),
//]
